name: E2E on Chrome
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [21.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            try {
              const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              if (res.status !== 200) {
                core.setFailed(`Failed to list artifacts: ${res.status}`);
                return;
              }

              const artifactsToDelete = res.data.artifacts.filter(({ name }) => name === 'package');

              if (artifactsToDelete.length === 0) {
                console.log('No artifacts to delete.');
                return;
              }

              for (const { id } of artifactsToDelete) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: id,
                });
                console.log(`Deleted artifact with id: ${id}`);
              }
            } catch (error) {
              core.setFailed(`Action failed with error: ${error}`);
            }

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: ${{ vars.NEXT_PUBLIC_PUBLIC_URL }}
        env:
          CYPRESS_video: true
          CYPRESS_videoUploadOnPasses: false
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}
          SUPABASE_KEY_SERVICE: ${{ secrets.SUPABASE_KEY_SERVICE }}
          NEXT_PUBLIC_PUBLIC_URL: ${{ vars.NEXT_PUBLIC_PUBLIC_URL }}
          NEXT_PUBLIC_DEMO_USER_EMAIL: ${{ secrets.NEXT_PUBLIC_DEMO_USER_EMAIL }}
          NEXT_PUBLIC_DEMO_USER_PASSWORD: ${{ secrets.NEXT_PUBLIC_DEMO_USER_PASSWORD }}
          NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_PRODUCTION_URL: ${{ secrets.NEXT_PUBLIC_PRODUCTION_URL }}
          GOOGLE_RECAPTCHA_API_KEY: ${{ secrets.GOOGLE_RECAPTCHA_API_KEY }}
          GMAIL_LOGIN: ${{ secrets.GMAIL_LOGIN }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          E2E_LOGIN: ${{ secrets.E2E_LOGIN }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
