name: linting, testing
run-name: linting, testing
on:
    pull_request:
      branches:
        - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [20.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            .next
          key: ${{ runner.os }}-primes

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            .next
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run eslint

      - name: Run stylelint
        run: npm run stylelint
