name: Pre-cache Vercel Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  precache-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile and run urls.ts
        run: |
          npx tsc scripts/urls.ts
          node scripts/urls.js

      - name: Read URLs and request each one
        run: |
          while IFS= read -r url; do
            echo "Requesting $url..."
            curl -I "$url"
          done < urls.txt
